// <auto-generated />
using System;
using ForumApp.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ForumApp.Data.Migrations
{
    [DbContext(typeof(ForumAppDbContext))]
    [Migration("20231110112059_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ForumApp.Data.Models.Post", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasMaxLength(1500)
                        .HasColumnType("nvarchar(1500)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Posts");

                    b.HasData(
                        new
                        {
                            Id = new Guid("2470ad86-432c-4cdb-8f38-b37c7e19b588"),
                            Content = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer facilisis nisi non elementum vehicula. Nunc scelerisque erat urna, at mattis.",
                            Title = "my first post"
                        },
                        new
                        {
                            Id = new Guid("36a2e6ac-4d0e-4451-ba65-4fec4ed79528"),
                            Content = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Curabitur pharetra erat ante, ac finibus massa sodales vehicula. Ut iaculis tortor quis imperdiet imperdiet. In euismod.",
                            Title = "my second post"
                        },
                        new
                        {
                            Id = new Guid("a8d56cb9-1382-4b6f-b145-61401b0310a5"),
                            Content = "Translations: Can you help translate this site into a foreign language ? Please email us with details if you can help.",
                            Title = "my third post"
                        },
                        new
                        {
                            Id = new Guid("ce96ef2a-6ca3-4415-a1b7-868962b900e7"),
                            Content = "Section 1.10.32 of \"de Finibus Bonorum et Malorum\", written by Cicero in 45 BC\r\n\"Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt explicabo. Nemo enim ipsam voluptatem quia voluptas sit aspernatur aut odit aut fugit, sed quia consequuntur magni dolores eos qui ratione voluptatem sequi nesciunt. ",
                            Title = "my fourth post"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
